Repository voorhoede/head-start, pull requests merged in 2025-01, with the labels that each got.

#209 feature: custom fonts with preloading
  package-lock.json
  package.json
  src/assets/fonts.ts
  src/components/PerfHead/PerfHead.astro
  src/components/PerfHead/PerfHead.test.ts
  src/components/PerfHead/README.md
  src/layouts/Default.astro
Labels: performance

#217 docs: assets (pubic and processed)
  README.md
  docs/assets.md
  docs/project-structure.md
  package.json
  public/README.md
  src/assets/README.md
  src/components/Icon/README.md
Labels: documentation

#230 feature: basic editable responsive menu
  config/datocms/migrations/1706210000_translations.ts
  config/datocms/migrations/1734713241_basicMenu.ts
  datocms-environment.ts
  src/assets/icons/menu.svg
  src/components/AppLogo/AppLogo.astro
  src/components/AppLogo/README.md
  src/components/Icon/index.ts
  src/components/IconButton/IconButton.astro
  src/components/LocaleSelector/LocaleSelector.astro
  src/components/LocaleSelector/README.md
  src/components/SearchLink/README.md
  src/components/SearchLink/SearchLink.astro
  src/components/SeoHead.astro
  src/components/UnstyledList/README.md
  src/components/UnstyledList/UnstyledList.astro
  src/layouts/AppHeader/AppHeader.astro
  src/layouts/AppMenu/AppMenu.astro
  src/layouts/AppMenu/AppMenu.client.ts
  src/layouts/AppMenu/AppMenu.fragment.graphql
  src/layouts/AppMenu/AppMenuItem.astro
  src/layouts/AppMenu/README.md
  src/layouts/Default.astro
  src/layouts/PerfHead/PerfHead.astro
  src/layouts/PerfHead/PerfHead.test.ts
  src/layouts/PerfHead/README.md
  src/layouts/README.md
  src/layouts/SeoHead/README.md
  src/layouts/SeoHead/SeoHead.astro
  src/layouts/default.query.graphql
Labels: 🚏 routing

#222 refactor: middleware as atomic files + docs
  docs/project-structure.md
  docs/routing.md
  src/middleware.ts
  src/middleware/README.md
  src/middleware/datocms.ts
  src/middleware/i18n.ts
  src/middleware/index.ts
  src/middleware/preview.ts
  src/middleware/redirects.ts
  src/pages/api/preview/enter.ts
  src/pages/api/preview/exit.ts
  tsconfig.json
Labels: 🚏 routing

#245 fix: use dynamic IDs in migrations
  config/datocms/migrations/1730405111_linkRecords.ts
  config/datocms/migrations/1730927867_fileModel.ts
  config/datocms/migrations/1734363388_actionBlock.ts
  config/datocms/migrations/1734713241_basicMenu.ts
Labels: bug
